spring:
  rabbitmq:
     addresses: localhost:5672
     password: guest
     username: guest
     listener:
       simple:
         concurrency: 4
         max-concurrency: 8
         prefetch: 162
       concurrency: 4
       max-concurrency: 8
       prefetch: 162