server:
  port: 8090

spring:
  rabbitmq:
     addresses: localhost:5672
     password: guest
     username: guest
     listener:
       simple:
         concurrency: 4
         max-concurrency: 8
         prefetch: 162
       concurrency: 4
       max-concurrency: 8
       prefetch: 162
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        input:
          destination: foodOrders
          group: foodOrdersIntakeGroup
        test-bind:
          destination: foodOrders2
          group: foodOrdersIntakeGroup2
        foodOrdersChannel:
          destination: foodOrders
      rabbit:
        bindings:
          foodOrdersChannel:
            producer:
              bindingRoutingKey:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

metadata.store.jdbc.table-prefix: rabbit_

spring.h2.console.enabled: true
spring.h2.console.path: /h2

eureka:
  client:
    enabled: false

security:
  ignored: /**